name: anydrawer
description:
  A flutter package to show drawer from any where in the app by providing context.
  It eliminates the need to use scaffold to show drawer.
version: 1.0.2
homepage: https://github.com/oi-narendra/anydrawer

environment:
  sdk: ">=3.0.1 <4.0.0"
  flutter: ">=2.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  dart_code_metrics: ^5.7.4
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0+1

flutter: null
# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#

screenshots:
  - description: "Example in web"
    path: screenshots/sample1.gif
  - description: "Examples in mobile"
    path: screenshots/sample2.gif
