name: anydrawer
description:
  Introducing a revolutionary Flutter package that allows you to display a drawer from anywhere within your app, simply by providing context.

  Say goodbye to the constraints of using a scaffold to show a drawer.

  With this package, you gain the flexibility to display a drawer from any point in your app, enhancing your app's navigation and user experience.
  Whether you're building a complex app with numerous screens or a simple one with a few, this package is designed to make your development process smoother and your app more user-friendly.

  Try it today and experience the difference!

version: 1.0.4
homepage: https://github.com/oi-narendra/anydrawer

environment:
  sdk: ">=3.0.1 <4.0.0"
  flutter: ">=2.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  dart_code_metrics: ^5.7.4
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0+1

flutter: null
# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#

screenshots:
  - description: "Example in mobile"
    path: screenshots/scnsht1.png
  - description: "Examples in Web"
    path: screenshots/scnsht2.png
