name: Publish to pub.dev

on:
  push:
    branches:
      - main
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*" # tag-pattern on pub.dev: 'v'

env:
  PUB_HOSTED_URL: https://pub.dartlang.org
  PUB_CACHE: /github/workspace/.pub-cache

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: "3.13.0"
      - name: Install dependencies
        run: flutter pub get
      - name: Run tests
        run: flutter test

  publish:
    needs: test
    permissions:
      id-token: write # Required for authentication using OIDC
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: "3.13.0"
      - name: Install dependencies
        run: flutter pub get
      - name: Create flutter publishing token flutter
        run: |
          set -eo pipefail
          PUB_TOKEN=$(curl --retry 5 --retry-connrefused -sLS "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=https://pub.dev" -H "User-Agent: actions/oidc-client" -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" | jq -r '.value')
          echo "PUB_TOKEN=${PUB_TOKEN}" >> $GITHUB_ENV
          export PUB_TOKEN
          flutter pub token add https://pub.dev --env-var PUB_TOKEN
      - name: Publish to pub.dev
        run: flutter pub publish --force
